version: '3.1'
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - 80:5000
    restart: always
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=production
      - PORT=5000
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
